### ISSUE TITLE
stacking using another pretrained model?

### ISSUE THREAD

**Issue by AlJohri** [caioaao/wolpert#18]
hey @caioaao, qq- I was wondering if your library would make this particular use case a little cleaner. I have a paraphrase detection model that is trained on SemEval data. I'm using the output of this model as input to a LogisticRegression trained on another dataset of headlines.

I converted the pretrained model into a `Transformer` and created a new Pipeline simulating a stacked model.

**pretrained model/pipeline**
```python
from paradox import necessary_imports_for_pickle_to_load

with open("paradox/model.pickle", 'rb') as f:
    model = pickle.load(f)

from tqdm import tqdm
import numpy as np
from sklearn.base import BaseEstimator

class ParadoxModel(BaseEstimator):
    
    def __init__(self, model):
        self.model = model
    
    def fit(self, X, y):
        return self

    def transform(self, X):
        a = []
        for x in tqdm(X):
            a.append(self._transform(x))
        return np.array(a).reshape(-1, 1) 

    def _transform(self, x):
        return model.predict([x])[0]
```

**new pipeline**
```python
from sklearn.linear_model import LogisticRegression

pipeline = Pipeline(steps=[
    ('paradox', ParadoxModel(model)),
    ('clf', LogisticRegression())
])
pipeline.fit(X_train, y_train)
```

I can definitely retrain the paradox model but it takes a different data source (the SemEval paraphrase detection data) while my logit is trained on news headline pairs.

Any way wolpert can help with this? And if not, any better ways of doing this come to mind?

Thanks for your time!

**Comment by caioaao** [comment]
I don't think `wolpert` would help with stacking pretrained models, as stacking is basically a bunch of strategies for training and generating predictions from lower layers to avoid data leakage. Also I don't think there's a better way right now to do what you are trying to do.

There were some discussion on scikit learn (scikit-learn/scikit-learn#8370) about an API for "freezing" estimators that would do exactly what you want, but I think they are not working on this right now
